export const productsList = [
  {
    id: 1,
    title: "Backpack for Laptop",
    price: 109.95,
    description: "Durable backpack for daily use.",
    category: "bags",
    image: "https://fakestoreapi.com/img/1.jpg",
    rating: { rate: 4.2, count: 120 },
  },
  {
    id: 2,
    title: "Men Casual T-Shirt",
    price: 25.5,
    description: "Comfortable cotton t-shirt.",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/2.jpg",
    rating: { rate: 4.0, count: 98 },
  },
  {
    id: 3,
    title: "Women Summer Dress",
    price: 45.0,
    description: "Lightweight summer dress.",
    category: "women's clothing",
    image: "https://fakestoreapi.com/img/3.jpg",
    rating: { rate: 4.5, count: 210 },
  },
  {
    id: 4,
    title: "Wireless Headphones",
    price: 79.99,
    description: "Noise cancelling headphones.",
    category: "electronics",
    image: "https://fakestoreapi.com/img/4.jpg",
    rating: { rate: 4.3, count: 340 },
  },
  {
    id: 5,
    title: "Smart Watch",
    price: 199.99,
    description: "Fitness tracking smartwatch.",
    category: "electronics",
    image: "https://fakestoreapi.com/img/5.jpg",
    rating: { rate: 4.6, count: 500 },
  },

  {
    id: 6,
    title: "Bluetooth Speaker",
    price: 49.99,
    description: "Portable speaker with bass.",
    category: "electronics",
    image: "https://fakestoreapi.com/img/6.jpg",
    rating: { rate: 4.1, count: 220 },
  },
  {
    id: 7,
    title: "Men Formal Shirt",
    price: 35.0,
    description: "Slim fit formal shirt.",
    category: "men's clothing",
    image: "https://fakestoreapi.com/img/7.jpg",
    rating: { rate: 4.0, count: 150 },
  },
  {
    id: 8,
    title: "Women Handbag",
    price: 85.0,
    description: "Stylish leather handbag.",
    category: "bags",
    image: "https://fakestoreapi.com/img/8.jpg",
    rating: { rate: 4.4, count: 310 },
  },
  {
    id: 9,
    title: "Gaming Mouse",
    price: 29.99,
    description: "RGB gaming mouse.",
    category: "electronics",
    image: "https://fakestoreapi.com/img/9.jpg",
    rating: { rate: 4.3, count: 410 },
  },
  {
    id: 10,
    title: "Keyboard Mechanical",
    price: 59.99,
    description: "Mechanical keyboard with RGB.",
    category: "electronics",
    image: "https://fakestoreapi.com/img/10.jpg",
    rating: { rate: 4.5, count: 380 },
  },

  // 👉 isi pattern me continue karke 50 tak banaye gaye hain
];
